title:            Jing Wei
description:      It is our light, not our darkness that frightens us.
url:              # Site url.
github_card:      # you need to replace the current github-card. ( leave blank if unwanted. )
google_analytics: UA-73260325-1  # (leave blank if unwanted )
disqus_shortname:                # disqus and duoshuo is an alternative option. ( leave blank if unwanted)
duoshuo_shortname: Jing Wei

kramdown:
  input:    GFM
  syntax_highlighter:    rouge

defaults:
    -
        scope:
            path:    "_posts"
            type:    "posts"
        values:
          layout:    "post"
          disqus:    "y"
          author:    "Jing Wei"
